# Generated by Django 3.1.1 on 2021-03-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
