# Generated by Django 3.1.1 on 2021-03-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('1', 'Fashion'), ('2', 'Toys'), ('3', 'Electronics'), ('4', 'Home')], help_text='Choose a category.', max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(help_text='Add a short description of the item.', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional. Provide an "url" for an image for the listing.'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(help_text='Provide the name of the new item.', max_length=64),
        ),
    ]
