# Generated by Django 3.1.1 on 2021-03-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210313_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.FloatField(help_text='Set the initial bid.'),
        ),
    ]
